### ISSUE TITLE
Load-balancing of SCTP only takes port into account.

### ISSUE THREAD

**Issue by tedlean** [Nordix/nfqueue-loadbalancer#19]
It has been seen at some users that all SCTP connection ends up on the same target.
 
It is related to an early try for getting SCTP multihoming to work. Here a primary and secondary IP-connection is used for the same SCTP association. Each connection has a different IP-address as source and destination.  The used Src-port was expected to be the same for both connections, so thus by only hashing the ports the two IP-connections (primary and secondary) would end up at the same target. 

This is stated in the documentation:
For a multihomed SCTP association the addresses (both source and dest) are different for the paths but the ports are always the same. So for SCTP the nfqlb hash on ports only.

A real use-case has now shown a scenario where the same src-port is used by many clients and only the src. IP-address differs. 
All these connection ends up at the same target, which then gets overloaded. 

Today the SCTP MH connection bundling is solved by other means, Therefore the load-balancing for SCTP should be changed to take both the src- ports and src-IP into account.

BR
Leif Andersen

**Comment by LionelJouin** [comment]
Using SCTP, source and destination IPs are ignored just before hashing: https://github.com/Nordix/nfqueue-loadbalancer/blob/1.1.4/src/lib/iputils.c#L372

**Comment by tedlean** [comment]
Right, could we have this exclusion of the IPs for the hashing removed. 
Or at least removed by an ENV-setting if it has to be kept, although I am not sure that leaving out the IP-addresses really can be used anywhere.
